apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-telemetry-data
  namespace: agent-telemetry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
