apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: agent-telemetry-server-token
    namespace: agent-telemetry
spec:
    secretTemplates:
        - name: agent-telemetry-server-token
          stringData:
            token: ENC[AES256_GCM,data:ZuTomxyYKcCM5vEjrQN6G19nwNHXiQsHLk+6JPAUmtEf52BZcBwv8o5vnTLmRpfT1j3OIZXUK2puFy1Kg65r2g==,iv:JCpTMtU3VTyHBpvfRaoE+YpbdfZuaWBJOuBphVvmI5E=,tag:20QNx2hojWzsaCe5Zv9zhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcGZrT3FhaVB5cjV1ZHhk
            VUo0dStnaVZqZW1ucnJnTUdWaS85RUFLVTBJCkNBV0ZEMndPR1lmRHYzRWEwcGRE
            WlVHbkZMRytrRDE0Z3VCNDYrMkk0N0EKLS0tIHd3QmtQM2J4aXhrMVpqTXRQaFFl
            bnF2Q1QyU0NQYlJCa0ZacUUxNHF3V0kK9VAbUX2MN+y8+V3AKtaTFtLcZzGRBlcE
            UVyTdDfZFOyguwUIaReLKjWb3PUDAkGCtGjdoBYezxYYZ5zzI1TTMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0w47shfc9mntx8rgzqjq8qc500cmunxj7pq8nfdt40wjn2gjqzq0c3m9d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-10T14:45:07Z"
    mac: ENC[AES256_GCM,data:gCupcAiSx3iPWplpo/eX3efuSS8WiGNhieFfDNGrjJ4F0RnZd0XE2wNHfXaFFtft9KYzNhbF7KTo3ugddN8GuqvA/OGjdCk0QZTOanRd0qWj1T3t62pM+FlIIuN4U4g1MQWtOZWo2fbMVFk+3FG9l5dqTgpnJUv4cqo7cpfHRNI=,iv:Pdp3OmJbX4WArkLx6jl+Jyx8VNxVInf63UEG6GkAfco=,tag:lfcPHDXTd3nDYp5u8zQpAA==,type:str]
    version: 3.13.0
