apiVersion: v1
kind: Service
metadata:
  name: agent-telemetry
  namespace: agent-telemetry
  labels:
    app: agent-telemetry
spec:
  type: ClusterIP
  selector:
    app: agent-telemetry
  ports:
    - name: ingest
      port: 8443
      targetPort: ingest
      protocol: TCP
    - name: grafana
      port: 3000
      targetPort: http
      protocol: TCP
